name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Selecct Xcode 13.3.1
        run: sudo xcode-select -s '/Applications/Xcode_13.3.1.app/Contents/Developer'

      - name: Build
        run: xcodebuild build -destination 'name=iPhone 13' -scheme 'SwiftUI-Common'

      - name: Test
        run: xcodebuild test -destination 'name=iPhone 13' -scheme 'SwiftUI-Common'
